[package]
name = "bitbang-dap"
version = "0.1.0"
edition = "2024"

[dependencies]
dap-rs = { git = "https://github.com/bugadani/dap-rs", rev = "8a5049d528b866e65aa1c343b38e1d8776a3d626" }
defmt = { version = "1.0", optional = true }
log = { version = "0.4", optional = true }
