[package]
name = "bitbang-dap"
version = "0.1.0"
edition = "2024"

[dependencies]
dap-rs = { path = "../dap-rs" }
defmt = { version = "1.0", optional = true }
log = { version = "0.4", optional = true }
